import { Link } from 'react-router-dom'
import { ArrowRight, Sparkles, Clock, Users, Vote, Landmark, FileText, BookOpen, MessageSquare } from 'lucide-react'

const DAYS = [
  {
    day: 'Monday',
    icon: Sparkles,
    title: 'Start the week with NRI',
    time: '8:00 AM',
    narrative: 'María opens Communis on her phone while drinking coffee. The NRI compass greets her: "Good morning, Evergreen. The hiring committee hasn\'t met in 2 weeks — Roberto\'s review is coming up." She messages James to schedule it. Done before her first client.',
    color: 'bg-grove-50 border-grove-100',
  },
  {
    day: 'Tuesday',
    icon: Clock,
    title: 'Log hours, check equity',
    time: 'End of shift',
    narrative: 'Fatima finishes her shift and opens the app. Her hours auto-imported from payroll. She checks her Member Story page: $5,340 in equity. The narrative reads: "Each hour you work strengthens both the cooperative and your own ownership stake." She smiles.',
    color: 'bg-warmth-50 border-warmth-100',
  },
  {
    day: 'Wednesday',
    icon: Users,
    title: 'Hiring committee meets',
    time: '2:00 PM',
    narrative: 'James chairs the hiring committee on Zoom. The agenda was set in Communis — Roberto\'s 4th milestone review. They draft a recommendation using the meeting template. Minutes are saved automatically. The committee votes: recommend Roberto for full membership.',
    color: 'bg-commons-50 border-commons-100',
  },
  {
    day: 'Thursday',
    icon: Vote,
    title: 'Roberto practices voting',
    time: 'Lunch break',
    narrative: 'Roberto — still a candidate — opens Communis and tries a Rehearsal Vote. He picks "consensus" and sees what happens when someone blocks. The explanation reads: "A block means \'I believe this would cause serious harm.\' The group must address the concern." He gets it now. When his membership vote comes, he\'ll understand the process.',
    color: 'bg-terra-50 border-terra-100',
  },
  {
    day: 'Friday',
    icon: Landmark,
    title: 'Patronage vote passes',
    time: '4:00 PM',
    narrative: 'David casts the final vote on the Q4 patronage distribution — $18,400 split five ways based on hours. The vote passes. Communis triggers the patronage engine: calculates each member\'s share, posts to their ICAs, and queues Stripe payouts to their bank accounts. 1099-PATRs will be generated by month-end. What used to take David 6 hours in Excel took 30 seconds.',
    color: 'bg-grove-50 border-grove-100',
  },
  {
    day: 'Saturday',
    icon: BookOpen,
    title: 'Ana Lucía reads about cooperatives',
    time: 'Morning',
    narrative: 'Ana Lucía opens the Library and starts reading "Collective Courage" — the history of Black cooperative economics. She bookmarks it. Then she writes a Communio insight: "Our Spanish-language onboarding buddy system increased candidate completion from 60% to 90%." She submits it for steward review. A cleaning co-op in Brooklyn will read it next week.',
    color: 'bg-warmth-50 border-warmth-100',
  },
  {
    day: 'Sunday',
    icon: MessageSquare,
    title: 'Rest, reflect, belong',
    time: 'Evening',
    narrative: 'Evergreen\'s NRI weekly rhythm note appears in the dashboard: "This week: 1 governance decision made, all committees active, Roberto completed milestone 4, patronage distributed. Participation: 100%. The cooperative is healthy." Nobody reads it on Sunday. But on Monday, it\'ll be there — a quiet record that five people, working together, built something worth belonging to.',
    color: 'bg-commons-50 border-commons-100',
  },
]

export default function WeekAtCoopPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <div className="text-center mb-12">
        <h1 className="font-display text-3xl md:text-4xl font-bold text-gray-900">
          A Week at a Cleaning Co-op
        </h1>
        <p className="mt-4 text-gray-500 leading-relaxed max-w-xl mx-auto">
          Evergreen Workers Co-op — 5 member-owners in Portland, Oregon.
          This is what a week looks like when your cooperative runs on Communis.
        </p>
      </div>

      <div className="space-y-6">
        {DAYS.map(day => (
          <div key={day.day} className={`p-6 rounded-2xl border ${day.color}`}>
            <div className="flex items-center gap-3 mb-3">
              <day.icon size={18} className="text-grove-600" />
              <div>
                <p className="font-display text-lg font-semibold text-gray-900">{day.day}</p>
                <p className="text-xs text-gray-400">{day.title} · {day.time}</p>
              </div>
            </div>
            <p className="text-sm text-gray-600 leading-relaxed">{day.narrative}</p>
          </div>
        ))}
      </div>

      <div className="mt-12 text-center">
        <p className="font-display text-lg font-semibold text-gray-900 mb-2">
          This is what cooperative technology should feel like.
        </p>
        <p className="text-sm text-gray-500 mb-6">
          Not a dashboard. Not a spreadsheet. A living system that knows your co-op,
          educates your members, and makes democracy feel natural.
        </p>
        <Link to="/demo" className="calm-button-primary inline-flex items-center gap-2">
          Try the Demo <ArrowRight size={16} />
        </Link>
      </div>
    </div>
  )
}
